title: "Korven Vaeltajat â€“ Joutsenolaista alkuvoimaa" # the name of your site, e.g. ACME Corp.
permalink: /:slug
collections:
  articles:
    output: true
    permalink: /ajankohtaista/:path
  events:
    output: true
    permalink: /tapahtumat/:path

exclude:
  - .env
  - Makefile
  - Gemfile
  - Gemfile.lock
  - sync.rb
  - README.md
